# config for analysis

# conda environment file
environment: environment.yml

# most CPUs to ever use at once
max_cpus: 8

# amplicons sequenced by PacBio
amplicons_Wuhan_Hu_1: data/PacBio_amplicon_Wuhan_Hu_1.gb
amplicons_E484K: data/PacBio_amplicon_E484K.gb
amplicons_N501Y: data/PacBio_amplicon_N501Y.gb
amplicons_B1351: data/PacBio_amplicon_B1351.gb

# how to parse the amplicon
feature_parse_specs_Wuhan_Hu_1: data/feature_parse_specs_Wuhan_Hu_1.yaml
feature_parse_specs_E484K: data/feature_parse_specs_E484K.yaml
feature_parse_specs_N501Y: data/feature_parse_specs_N501Y.yaml
feature_parse_specs_B1351: data/feature_parse_specs_B1351.yaml

# do we get the sequencing data from the 'HutchServer' or 'SRA'?
seqdata_source: HutchServer

# list of PacBio sequencing runs linking barcodes to variants
pacbio_runs: data/PacBio_runs.csv

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

# wildtype sequence of mutagenized gene
wildtype_sequence: data/wildtype_sequence.fasta
site_number_offset: 330  # add this to sequential sites to get RBD numbering

# pdb for mapping
pdb_6m0j: data/6m0j.pdb

# URLs from which we download binding & expression of mutants & variants
mut_bind_expr_url: https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS/master/results/single_mut_effects/single_mut_effects.csv
delta_mut_bind_expr_url: https://raw.githubusercontent.com/jbloomlab/SARS-CoV-2-RBD_Delta/main/results/final_variant_scores/final_variant_scores.csv?token=ABECTFLN4NIKEVJGSVBAVM3BTRX66
mut_antibody_escape_url: https://raw.githubusercontent.com/jbloomlab/SARS2_RBD_Ab_escape_maps/main/processed_data/escape_data.csv


# output directories / files
summary_dir: results/summary
mut_bind_expr: results/prior_DMS_data/mutant_ACE2binding_expression.csv
delta_mut_bind_expr: results/prior_DMS_data/delta_mut_bind_expr.csv
mut_antibody_escape: results/prior_DMS_data/mutant_antibody-escape.csv
figs_dir: results/figures
ccs_dir: results/ccs
process_ccs_dir: results/process_ccs
processed_ccs_file_Wuhan_Hu_1: results/process_ccs/processed_ccs_Wuhan_Hu_1.csv
processed_ccs_file_E484K: results/process_ccs/processed_ccs_E484K.csv
processed_ccs_file_N501Y: results/process_ccs/processed_ccs_N501Y.csv
processed_ccs_file_B1351: results/process_ccs/processed_ccs_B1351.csv
variants_dir: results/variants
nt_variant_table_file_Wuhan_Hu_1: results/variants/nucleotide_variant_table_Wuhan_Hu_1.csv
nt_variant_table_file_E484K: results/variants/nucleotide_variant_table_E484K.csv
nt_variant_table_file_N501Y: results/variants/nucleotide_variant_table_N501Y.csv
nt_variant_table_file_B1351: results/variants/nucleotide_variant_table_B1351.csv
codon_variant_table_file_Wuhan_Hu_1: results/variants/codon_variant_table_Wuhan_Hu_1.csv
codon_variant_table_file_E484K: results/variants/codon_variant_table_E484K.csv
codon_variant_table_file_N501Y: results/variants/codon_variant_table_N501Y.csv
codon_variant_table_file_B1351: results/variants/codon_variant_table_B1351.csv
counts_dir: results/counts
variant_counts_file: results/counts/variant_counts.csv
expression_sortseq_dir: results/expression_meanF
expression_sortseq_file: results/expression_meanF/bc_expression.csv
Titeseq_Kds_dir: results/binding_Kd
Titeseq_Kds_file: results/binding_Kd/bc_binding.csv
final_variant_scores_dir: results/final_variant_scores
final_variant_scores_mut_file: results/final_variant_scores/final_variant_scores.csv
epistatic_shifts_dir: results/epistatic_shifts
UShER_dir: results/UShER_SARS-CoV-2
UShER_tree: results/UShER_SARS-CoV-2/public-latest.all.masked.pb
UShER_tree_nwk_gz: results/UShER_SARS-CoV-2/public-latest.all.nwk.gz
UShER_tree_nwk: results/UShER_SARS-CoV-2/public-latest.all.nwk
UShER_ref: results/UShER_SARS-CoV-2/NC_045512.2.fa
UShER_gtf: results/UShER_SARS-CoV-2/ncbiGenes.gtf
UShER_annotated_subs: results/UShER_SARS-CoV-2/annotated_subs.tsv
UShER_parsed_subs_N501Y: results/UShER_SARS-CoV-2/parsed_subs_N501Y.csv


# parameters for running PacBio `ccs` program
min_ccs_accuracy: 0.999
min_ccs_passes: 3
min_ccs_length: 50
max_ccs_length: 5000

# max error rate in gene / barcode CCSs retained for consensu building
max_error_rate: 0.0001

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0

# Input files for analyses from the data subdirectory
RBD_sites: data/RBD_sites.csv
